format_macro_matchers = true
format_strings = true
imports_layout = "HorizontalVertical"
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
